// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;
using Cratis.Specifications;
using Cratis.Stage.Contracts.Rendering;
using Cratis.Stage.Rendering.Cratis.for_CratisArtifactRenderPlanner.given;
using Xunit;

namespace Cratis.Stage.Rendering.Cratis.for_CratisArtifactRenderPlanner;

/// <summary>
/// A model without `not` keeps its two-valued policy rendering: without negation, deny-on-unknown decides exactly
/// as treating an unknown comparison as false, so the generated bytes do not change.
/// </summary>
public class when_rendering_authorization_without_negation : Specification
{
    ArtifactRenderPlan _plan = null!;
    string _policies = null!;

    void Because()
    {
        _plan = invoice_model.Plan(invoice_model.Compile(when_rendering_portable_authorization.Source));
        _policies = Encoding.UTF8.GetString(_plan.Artifacts.Single(artifact => artifact.RelativePath.EndsWith("Policies.cs", StringComparison.Ordinal)).Bytes.AsSpan());
    }

    [Fact] void should_plan_the_application() => _plan.Success.ShouldBeTrue();
    [Fact] void should_keep_the_two_valued_claim_comparison() => _policies.Contains("PolicyValues.Match(context, \"owner\", ", StringComparison.Ordinal).ShouldBeTrue();
    [Fact] void should_emit_no_three_valued_helpers() => (_policies.Contains("Truth(", StringComparison.Ordinal) || _policies.Contains("PolicyValues.Not(", StringComparison.Ordinal) ||
        _policies.Contains("bool?", StringComparison.Ordinal)).ShouldBeFalse();
}
