// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;
using System.Text.Json;
using Cratis.Screenplay.Semantics;
using Cratis.Stage.Rendering.Cratis.Naming;
using Cratis.Stage.Rendering.Cratis.Semantics;

namespace Cratis.Stage.Rendering.Cratis.Scene;

/// <summary>
/// Renders the module that binds a composed Scene to the generated Arc proxies.
/// </summary>
/// <remarks>
/// <para>
/// Scene resolves the <c language="json">command</c> and <c language="json">query</c> properties on an element through its own binding
/// registry, by name. This module is the other half of that: it imports the proxies the Arc proxy generator
/// emits for this application and registers them under the semantic names the Scene payload refers to.
/// </para>
/// <para>
/// No HTTP route appears here, or anywhere else in an emitted TypeScript file. A route is a runtime fact owned
/// by Arc, and a generated application that re-derived one from a naming convention would drift from the
/// endpoints Arc actually registers the moment either convention changed.
/// </para>
/// <para>
/// The proxies themselves are build output, not planned artifacts: the generator stamps a timestamp into their
/// headers, so they are excluded from the plan and regenerated by the build instead.
/// </para>
/// </remarks>
internal static class SceneBindingsRenderer
{
    /// <summary>
    /// The planned artifact path.
    /// </summary>
    public const string RelativePath = "src/bindings.ts";

    /// <summary>
    /// Renders the binding registration module for the whole application.
    /// </summary>
    /// <param name="context">The indexed semantic application.</param>
    /// <returns>The generated module text.</returns>
    /// <remarks>
    /// The proxy generator writes a proxy beside the source it was generated from, so a proxy is imported from
    /// the slice folder that declares it rather than from the project root. Each of those folders carries an
    /// index that re-exports it, which is what makes the folder itself the import.
    /// </remarks>
    public static string Render(SemanticApplicationContext context)
    {
        var commands = context.Commands.Values
            .Select(_ => (_.Name, Module: Module(context, _.Id)))
            .DistinctBy(_ => _.Name, StringComparer.Ordinal)
            .OrderBy(_ => _.Name, StringComparer.Ordinal)
            .ToArray();
        var queries = context.Queries.Values
            .OrderBy(_ => _.Name, StringComparer.Ordinal)
            .ThenBy(_ => _.Id.ToString(), StringComparer.Ordinal)
            .Select((query, index) => (query.Name, Identity: query.Id.ToString(),
                Export: Identifiers.ToPascalCase(query.Name), Module: Module(context, query.Id), Alias: $"__sceneQuery{index}"))
            .ToArray();

        var builder = new StringBuilder()
            .Append("// Registers the generated Arc proxies under the names the composed Scene refers to.\n")
            .Append("// Scene resolves bindings by name; routes stay owned by Arc at runtime.\n")
            .Append(queries.Length > 0
                ? "import { registerCommands, registerQueryIdentity } from '@cratis/scene.components';\n"
                : "import { registerCommands } from '@cratis/scene.components';\n");

        foreach (var (name, module) in commands)
        {
            builder.Append("import { ").Append(name).Append(" } from '").Append(module).Append("';\n");
        }

        foreach (var query in queries)
        {
            builder.Append("import { ").Append(query.Export).Append(" as ").Append(query.Alias)
                .Append(" } from '").Append(query.Module).Append("';\n");
        }

        builder.Append('\n')
            .Append("registerCommands({")
            .AppendJoin(", ", commands.Select(_ => _.Name))
            .Append("});\n");
        foreach (var query in queries)
        {
            // Never collapse by name or duplicate into the legacy registry: exact consumers detect collisions,
            // and legacy table/singleResult consumers resolve a unique identity registration themselves.
            builder.Append("registerQueryIdentity(").Append(JsonSerializer.Serialize(query.Name)).Append(", ")
                .Append(JsonSerializer.Serialize(query.Identity)).Append(", ").Append(query.Alias).Append(");\n");
        }

        return builder.ToString();
    }

    /// <summary>
    /// The module a generated proxy is imported from, relative to this module.
    /// </summary>
    /// <param name="context">The indexed semantic application.</param>
    /// <param name="artifact">The command or query being registered.</param>
    /// <returns>The relative module specifier.</returns>
    static string Module(SemanticApplicationContext context, SemanticId artifact) =>
        "../" + string.Join('/', SliceNaming.FolderPath(context.DeclaringSlice(artifact).Path));
}
