// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;
using Cratis.Screenplay.Semantics;
using Cratis.Stage.Rendering.Cratis.Naming;
using Cratis.Stage.Rendering.Cratis.Semantics;

namespace Cratis.Stage.Rendering.Cratis.Scene;

/// <summary>
/// Renders the module that binds a composed Scene to the generated Arc proxies.
/// </summary>
/// <remarks>
/// <para>
/// Scene resolves the <c language="json">command</c> and <c language="json">query</c> properties on an element through its own binding
/// registry, by name. This module is the other half of that: it imports the proxies the Arc proxy generator
/// emits for this application and registers them under the semantic names the Scene payload refers to.
/// </para>
/// <para>
/// No HTTP route appears here, or anywhere else in an emitted TypeScript file. A route is a runtime fact owned
/// by Arc, and a generated application that re-derived one from a naming convention would drift from the
/// endpoints Arc actually registers the moment either convention changed.
/// </para>
/// <para>
/// The proxies themselves are build output, not planned artifacts: the generator stamps a timestamp into their
/// headers, so they are excluded from the plan and regenerated by the build instead.
/// </para>
/// </remarks>
internal static class SceneBindingsRenderer
{
    /// <summary>
    /// The planned artifact path.
    /// </summary>
    public const string RelativePath = "src/bindings.ts";

    /// <summary>
    /// Renders the binding registration module for the whole application.
    /// </summary>
    /// <param name="context">The indexed semantic application.</param>
    /// <returns>The generated module text.</returns>
    /// <remarks>
    /// The proxy generator writes a proxy beside the source it was generated from, so a proxy is imported from
    /// the slice folder that declares it rather than from the project root. Each of those folders carries an
    /// index that re-exports it, which is what makes the folder itself the import.
    /// </remarks>
    public static string Render(SemanticApplicationContext context)
    {
        var commands = context.Commands.Values
            .Select(_ => (_.Name, Module: Module(context, _.Id)))
            .DistinctBy(_ => _.Name, StringComparer.Ordinal)
            .OrderBy(_ => _.Name, StringComparer.Ordinal)
            .ToArray();
        var queries = context.Queries.Values
            .Select(_ => (_.Name, Module: Module(context, _.Id)))
            .DistinctBy(_ => _.Name, StringComparer.Ordinal)
            .OrderBy(_ => _.Name, StringComparer.Ordinal)
            .ToArray();

        var builder = new StringBuilder()
            .Append("// Registers the generated Arc proxies under the names the composed Scene refers to.\n")
            .Append("// Scene resolves bindings by name; routes stay owned by Arc at runtime.\n")
            .Append("import { registerCommands, registerQueries } from '@cratis/scene.components';\n");

        foreach (var (name, module) in commands.Concat(queries))
        {
            builder.Append("import { ").Append(name).Append(" } from '").Append(module).Append("';\n");
        }

        return builder
            .Append('\n')
            .Append("registerCommands({")
            .AppendJoin(", ", commands.Select(_ => _.Name))
            .Append("});\n")
            .Append("registerQueries({")
            .AppendJoin(", ", queries.Select(_ => _.Name))
            .Append("});\n")
            .ToString();
    }

    /// <summary>
    /// The module a generated proxy is imported from, relative to this module.
    /// </summary>
    /// <param name="context">The indexed semantic application.</param>
    /// <param name="artifact">The command or query being registered.</param>
    /// <returns>The relative module specifier.</returns>
    static string Module(SemanticApplicationContext context, SemanticId artifact) =>
        "../" + string.Join('/', SliceNaming.FolderPath(context.DeclaringSlice(artifact).Path));
}
